version: '3.8'
services:
  app:
    container_name: nestjs-app
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=nestjs-starter
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - sonarqube
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nestjs-starter
    ports:
      - '5432:5432'
  sonarqube:
    image: sonarqube
    environment:
      SONARQUBE_JDBC_USERNAME: admin
      SONARQUBE_JDBC_PASSWORD: admin
      SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/nestjs-starter
    ports:
      - '9000:9000'
    depends_on:
      - postgres
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: cloudwatch,secretsmanager
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
